name: 'Deploy Storybook'
on:
  push:
    branches:
      - main
    path:
      - 'src/stories/**'
      - '.storybook/**'
jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install npm packages
      run: npm ci
    - name: Deploy storybook
      run: npm run deploy-storybook
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
