name: 'ESLint'
description: 'ESLint 검사를 실행합니다.'
on:
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm ci
      - name: Run ESLint
        run: npm run lint
